# -*- coding: utf-8 -*-
"""Instant SERP checker - 0.2.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IGTqbY-W65rc-gsaQouxco4D1fCgAVor
"""

import requests

"""# Set up your search"""

#get API key at http://serpstack.com/?fpr=ttygt45bxbc55

#@title Enter your parameters
api_key = "" #@param {type:"string"}
query = "" #@param {type:"string"}
target_domain = "" #@param {type:"string"}
google_domain = "" #@param {type:"string"}
country_code = "" #@param {type:"string"}
language = "" #@param {type:"string"}
results = "" #@param {type:"string"}
device = "mobile" #@param ["desktop", "mobile", "tablet"]

"""## Send the request"""

#configure API parameters
params = {
  'access_key': api_key,
  'device': device,
  'gl': country_code,
  'hl': language,
  'auto_location': '1',
  'google_domain':google_domain,
  'query': query,
  'num': results
}

api_result = requests.get('http://api.serpstack.com/search', params)
api_response = api_result.json()

"""# Show results"""

#list top ten serps
for number, result in enumerate(api_response['organic_results'], start=1):
    if target_domain in result['domain']:
      print("=====================================================================")
      print("%s. %s - %s" % (number, result['domain'], result['title']))
      print("=====================================================================")
    else:
      print("%s. %s - %s" % (number, result['domain'], result['title']))